CuteBank-master/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :main, only: [:index] 

  resources :about, only: [:index] 

  resources :admin, only: [:index, :create]

  resources :user, only: [:index, :create]

  root to: 'main#index'

end

CuteBank-master/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

CuteBank-master/app/models/cash_machine.rb
# frozen_string_literal: true

class CashMachine < ApplicationRecord
  validates :cash_amount, presence: true

  def self.add_cash(amount)
    machine = CashMachine.find(1)

    machine.cash_amount = (machine.cash_amount += amount).round(2)

    machine.save!
  end

  # check if operation can be gone throuth and cash_machine balance won't be lower than zero
  def self.cash_available?(amount, user)
    machine = CashMachine.find(1)
    new_cash = (machine.cash_amount - amount).round(2)

    if new_cash < 0.0
      user.errors.add(:cash_machine, "The Cash machine doesn't have such sum")
      false
    else
      machine.cash_amount = new_cash
      machine.save!

      true
    end
  end

  # custom method to update cash_amount in cash_machine to receive error notifications
  def self.update_cash(amount, cash)
    if greater_or_equal_to_zero?(amount)
      cash.cash_amount = amount
      cash.save!

      true
    else
      cash.errors.add(:input, "can't be lower than zero!")
      false
    end
  end

  def self.greater_or_equal_to_zero?(amount)
    amount >= 0
  end
end

CuteBank-master/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  extend Devise::Models

  has_many :users_history_record

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :current_balance, presence: true

  def self.deposit(amount, user)
    if input_valid?(amount, user)
      user.current_balance = (user.current_balance += amount).round(2)
      user.save!

      true
    else
      false
    end
  end

  def self.withdraw(amount, user)
    if input_valid?(amount, user) && CashMachine.cash_available?(amount, user)
      user.current_balance = (user.current_balance -= amount).round(2)
      user.save!

      true
    else
      false
    end
  end

  def self.input_valid?(amount, user)
    if amount < 0.0
      user.errors.add(:input, "Number can't be lower than zero")

      false
    elsif amount == 0.0
      user.errors.add(:input, 'Adding or substracting zero will have no power')

      false
    else
      true
    end
  end
end

CuteBank-master/app/models/users_history_record.rb
# frozen_string_literal: true

class UsersHistoryRecord < ApplicationRecord
  belongs_to :user
end

CuteBank-master/app/controllers/about_controller.rb
class AboutController < ApplicationController

    def index
    
    end
end

CuteBank-master/app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  def index
    @cash = CashMachine.find(1)
  end

  def create
    @cash = CashMachine.find(1)

    unless params[:commit].nil?
      hash = params.require(:admin).permit(:cash_amount)
      cash_amount = hash[:cash_amount].to_f

      CashMachine.update_cash(cash_amount, @cash)

      render 'index'
    end
  end
end

CuteBank-master/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protected

  def after_sign_in_path_for(resource)
    user_index_path
  end

  def after_sign_out_path_for(resource)
    main_index_path
  end

  def require_admin
    unless current_user&.user_is_admin
      flash[:error] = 'You are not an admin'

      redirect_to user_index_path
    end
  end
end

CuteBank-master/app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  before_action :check_user
  
  def index 
  end

  #redirecting admin to admin user page and user to user main page, 
  #for not getting error while trying to access '/' and 'main'
  #in case of authenticated users  
  def check_user
    if current_user != nil 
      if current_user.user_is_admin?
        redirect_to controller: 'admin', action: 'index'
      else
        redirect_to controller: 'user', action: 'index'
      end
    end
  end
end

CuteBank-master/app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_admin

  def index
    @user = User.find(current_user.id)

    @record = @user.users_history_record.all
  end

  def create
    @user = User.find(current_user.id)

    @record = @user.users_history_record.all

    unless params[:commit].nil?
      if !choose_action
        render 'index'
      else
        redirect_to '/user'
      end
    end
  end

  def deposit(amount)
    @user = User.find(current_user.id)

    if User.deposit(amount, @user)
      CashMachine.add_cash(amount)

      @record = @user.users_history_record.build(operation_type: 'Deposit', amount: amount, balance_after: @user.current_balance)

      @record.save ? true : false
    else
      false
    end
  end

  def withdraw(amount)
    @user = User.find(current_user.id)

    if User.withdraw(amount, @user)
      @record = @user.users_history_record.build(operation_type: 'Withdraw', amount: amount, balance_after: @user.current_balance)

      @record.save ? true : false
    else
      false
    end
  end

  # choosing what action to do depending on :commit value
  private

  def choose_action
    hash = params.require(:user).permit(:current_balance, :commit)
    hash[:commit] = params[:commit]
    sum_int = hash[:current_balance].to_f

    case hash[:commit]
    when 'Withdraw'
      withdraw(sum_int)
    when 'Deposit'
      deposit(sum_int)
    end
  end

  # redirecting admin user to admin page

  def check_if_admin
    redirect_to controller: 'admin', action: 'index' if current_user.user_is_admin?
  end
end

CuteBank-master/app/helpers/about_helper.rb
module AboutHelper
end

CuteBank-master/app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

CuteBank-master/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

CuteBank-master/app/helpers/main_helper.rb
# frozen_string_literal: true

module MainHelper
end

CuteBank-master/app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

CuteBank-master/app/views/about/index.html.erb
<html>

<head>
  <title>CuteBank</title>
  <%= stylesheet_link_tag 'ClientInterface.css' %>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
</head>

<body>
  <div id="content">
    <div class="fon-content">
    </div>
  </div>
</body>

</html>

CuteBank-master/app/views/admin/index.html.erb
<html>

<head>
  <title>CuteBank</title>
  <%= stylesheet_link_tag 'ClientInterface.css' %>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
</head>

<body>
  <div id="content">
    <div class="fon-content">

      <div class="do_balance">
        
        <div class="input_balance">
          <div>Current cash amount in cash machine:
            <%= @cash.cash_amount%>
          </div>  
        </div>
      
        <div class="operation_balance">
          <div>
            <%= form_for :admin, :url => {:controller => :admin, :action => :index} do |f| %>
              <% if @cash.errors.any? %>
                <% @cash.errors.full_messages.each do |msg| %>
                  <div class= "alertCash ">
                    <%= msg%>
                  </div>
                <% end %>
              <% end %>
              <p >
                Set cash machine money amount  <br>
              <%= f.text_field :cash_amount %>
              </p>

              <p >
                <%= f.submit 'Submit'%>
              </p>
            <%end%>
          </div>  
        </div>

      </div>
    </div>
  </div>
</body>

</html>

CuteBank-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
  <div id="container">

  <div id="header">
    <div class="fon-head">


      <nav>
        <div class="logo-box">
          <h1 class="logo">
            <a href="/">
              <img src="/assets/logo-head.svg">
            </a>
          </h1>
        </div>
        <ul>
          <li>
            <%= link_to image_tag('/assets/icon-in.svg') + "Log out", destroy_user_session_path, method: :delete, class: "nav-link text-nowrap" %>
          </li>
        </ul>
      </nav>


    </div>
  </div>

  <% else %>
<div id="container">

  <div id="header">
    <div class="fon-head">


      <nav>
        <div class="logo-box">
          <h1 class="logo">
            <a href="/">
              <img src="/assets/logo-head.svg">
            </a>
          </h1>
        </div>
        <ul>
          <li>
            <%= link_to image_tag('/assets/icon-reg.svg') + "Registration", new_user_registration_path %>
            <div class="border-reg"></div>
          </li>
          <li>
            <%= link_to image_tag('/assets/icon-in.svg') + "Sign in", new_user_session_path %>
          </li>
          <li><a href="#"><img src="/assets/icon-lan.svg">Ru</a></li>
        </ul>
      </nav>


    </div>
  </div>
<% end %>
    <%= yield %>

     <div id="footer">
    <div class="fon-footer">


      <nav>
        <div class="logo-box">
          <h1 class="logo">
            <a href="/">
              <img src="/assets/logo-head.svg">
            </a>
          </h1>
        </div>
        <ul>
          <li>
          <%= link_to image_tag('/assets/icon-about.svg') + "About", about_index_path %>
            <div class="border-reg"></div>
          </li>
          <li><img class="icon-time" src="/assets/icon-time.svg"><span id="date_time"></span></li>
          <li><a href="#"><img src="/assets/icon-rights.svg">Rights reserved</a>
            <div class="border-reg"></div>
          </li>
        </ul>
      </nav>


    </div>
  </div>

</div>

<script>
    /* функция добавления ведущих нулей */
    /* (если число меньше десяти, перед числом добавляем ноль) */
    function zero_first_format(value) {
        if (value < 10) {
            value = '0' + value;
        }
        return value;
    }

    /* функция получения текущей даты и времени */
    function date_time() {
        var current_datetime = new Date();
        var day = zero_first_format(current_datetime.getDate());
        var month = zero_first_format(current_datetime.getMonth() + 1);
        var year = current_datetime.getFullYear();
        var hours = zero_first_format(current_datetime.getHours());
        var minutes = zero_first_format(current_datetime.getMinutes());
        var seconds = zero_first_format(current_datetime.getSeconds());

        return day + "." + month + "." + year + " " + hours + ":" + minutes + ":" + seconds;
    }

    /* каждую секунду получаем текущую дату и время */
    /* и вставляем значение в блок с id "current_date_time_block2" */
    setInterval(function() {
        document.getElementById('date_time').innerHTML = date_time();
    }, 1000);

</script>
  </body>
</html>

CuteBank-master/app/views/layouts/new.html.erb
<title>Cuteban</title>

CuteBank-master/app/views/main/index.html.erb
<html>

<head>
  <title>CuteBank</title>
  <%= stylesheet_link_tag 'startPage.css' %>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
</head>

<body>



  <div id="content">
    <div class="fon-content">
      <div class="welcome">
        <div class="become-client">
          <%= link_to "Become a client", new_user_registration_path %>
        </div>
        <div class="client-login">
          <%= link_to "Client Login", new_user_session_path %>
        </div>
      </div>

    </div>
  </div>

  


</body>

</html>

CuteBank-master/app/views/user/index.html.erb
<html>

<head>
  <title>CuteBank</title>
  <%= stylesheet_link_tag 'ClientInterface.css' %>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
</head>

<body>
  <div id="content">
    <div class="fon-content">

      <div class="do_balance">
        
        <div class="input_balance">
          <%= form_for :user, :url => {:controller => :user, :action => :index} do |f| %>
            <% if @user.errors.any? %>
              <% @user.errors.full_messages.each do |msg| %>
                <div class= "alertUser ">
                  <%= msg%>
                </div>
              <% end %>
            <% end %>
            <p >
              Enter the sum to withdraw or to deposit <br>
              <%= f.text_field :current_balance %>
            </p>

            <p >
              <%= f.submit 'Withdraw' %>
            </p>
            
            <p >
              <%= f.submit 'Deposit' %>
            </p>

          <%end%>
        </div>
      
        <div class="operation_balance">
          <div>
            <%if @record !=nil%>
              <%@record.each do |item|%>
                <%=item.operation_type%>
                <%=item.amount%>
                <%=item.balance_after%>
                <%=item.created_at%>
              <%end%>
            <% end %>
          </div>
        </div>

      </div>

      <div class="balance">
        <div>
          <%= @user.email %>
        </div>

        <div>
          <%=  @user.current_balance%>
        </div>
      </div>

    </div>
  </div>
</body>

</html>